@startuml Fatecaronas
left to right direction

' Actors
actor passenger as p
actor driver as d
actor admin as a

package "Fatecaronas" {
    ' Usecases
    usecase "Buscar viagens" as UC1
    usecase "Solicitar carona" as UC2
    usecase "Encerrar carona" as UC3
    usecase "Histórico de viagens" as UC5
    usecase "Avaliar usuários" as UC6
    usecase "Abrir viagem" as UC7
    usecase "Gerenciar requisição de carona" as UC8
    usecase "Encerrar viagem" as UC9
    usecase "Denunciar perfil" as UC10
    usecase "Bloquear perfil" as UC11
    usecase "Privar viagem" as UC18
    usecase "Solicitar amizade" as UC19
}

package "Fatecaronas admin dashboard" {
    usecase "Gerenciar servidor" as UC12
    usecase "Gerenciar extrato/transações" as UC13
    usecase "Gerenciar perfis" as UC14
    usecase "Efetuar bloqueio" as UC15
    usecase "Bloquear uso da conta" as UC16
    usecase "Realizar update" as UC17

}

' Relations
p --> UC1
p --> UC3
p --> UC5
UC1 <.. UC2: <<extends>>
UC3 ..> UC6: <<extends>>
UC9 ..> UC6: <<extends>>
UC6 ..> UC10: <<extends>>
UC6 ..> UC11: <<extends>>
UC6 ..> UC19 <<extends>>
UC7 ..> UC18: <<extends>>
d --> UC7
d --> UC8
d --> UC9
d --> UC5
a --> UC12
a --> UC13
a --> UC14
UC12 ..> UC17: <<extends>>
UC14 ..> UC15: <<extends>>
UC14 ..> UC16: <<extends>>

@enduml
